### ISSUE TITLE
Server Restart-Loop (Failed loading claim)

### ISSUE THREAD

**Issue by Dean0162** [itsmeow/ClaimIt#8]
Server failing to load claimed property!

Error occurred with a Server restart, no idea how to reproduce.

Server goes in a restart loop and creates Crash-logs every minute!

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 3/6/21 1:12 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ClaimIt API (claimitapi)
Caused by: java.lang.RuntimeException: There was no claim with the name b83afe95-10e5-4708-a1f6-0907e1d992de_332869017 found. This means data is missing/the world is corrupted/loading order is incorrect! Crashing to protect data.
	at dev.itsmeow.claimit.api.util.nbt.ClaimNBTUtil.readClaimNames(ClaimNBTUtil.java:47)
	at dev.itsmeow.claimit.api.group.Group.deserialize(Group.java:152)
	at dev.itsmeow.claimit.api.group.GroupManager.deserialize(GroupManager.java:100)
	at dev.itsmeow.claimit.api.ClaimItAPI.serverLoad(ClaimItAPI.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:797)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:307)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2016 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5102442560 bytes (4866 MB) / 6174015488 bytes (5888 MB) up to 6174015488 bytes (5888 MB)
	JVM Flags: 2 total; -Xmx6144M -Xms6144M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID           | Version      | Source                        | Signature                                |
	|:------- |:------------ |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA  | minecraft    | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA  | mcp          | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA  | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA  | forge        | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA  | attributefix | 1.0.4        | AttributeFix-1.12.2-1.0.4.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJAE | claimitapi   | 1.12.2-1.2.1 | claimitapi-1.12.2-1.2.1.jar   | None                                     |
	| LCHIJA  | claimit      | 1.12.2-1.2.1 | claimit-1.12.2-1.2.1.jar      | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 0 / 80; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

Removing the players Savefiles does not solve the issue.

Thanks in advance!

**Comment by itsmeow** [comment]
This is caused by a bug with the claimit claim delete command and the group system. The delete command currently fails to remove the claim from the group's claim list upon deletion and causes this crash. You'll need to use a tool like NBTExplorer to delete the claim from the group manually (stored in the claimit globaldata dat file inside world/data). I probably won't be able to release a fix for this for a while... so, I'm sorry.

**Comment by itsmeow** [comment]
The ClaimIt database design is really sub-par and causes issues like this one. It needs to be rewritten, which is why I've been avoiding updating ClaimIt. The whole mod needs to be pretty much remade.

**Comment by Desoroxxx** [comment]
Hello,

Is it being worked on?
